-- MySQL Script generated by MySQL Workbench
-- Wed Oct  9 10:45:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projeto_nis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_nis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_nis` DEFAULT CHARACTER SET utf8 ;
USE `projeto_nis` ;

-- -----------------------------------------------------
-- Table `projeto_nis`.`Membro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_nis`.`Membro` (
  `idMembro` INT NOT NULL AUTO_INCREMENT,
  `nomeMembro` VARCHAR(45) NOT NULL,
  `nisMembro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMembro`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
